name: Deploy to TEST instance

on:
  pull_request:
    types: [closed]

permissions:
  contents: write  # Required to create tags

jobs:
  deploy_to_test:
    name: Publish and Deploy to TEST
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Publish App from DEV
      id: publish_app
      uses: ServiceNow/sncicd-publish-app@2.0.1
      with:
        versionFormat: detect
      env:
        nowUsername: ${{ secrets.SN_DEV_USERNAME }}
        nowPassword: ${{ secrets.SN_DEV_PASSWORD }}
        nowSourceInstance: ${{ secrets.NOW_DEV_INSTANCE }}
        appSysID: ${{ secrets.APP_SYS_ID }}
          
    - name: Create Git Tag
      if: ${{ success() && steps.publish_app.outputs.newVersion }}
      uses: tvdias/github-tagger@v0.0.2
      with:
        repo-token: ${{ github.token }}
        tag: "${{ steps.publish_app.outputs.newVersion }}"

    - name: Install to TEST Instance
      if: ${{ success() && steps.publish_app.outputs.newVersion }}
      uses: ServiceNow/sncicd-install-app@1.0.0
      with:
        version: ${{ steps.publish_app.outputs.newVersion }}
      env:
        nowUsername: ${{ secrets.SN_TEST_USERNAME }}
        nowPassword: ${{ secrets.SN_TEST_PASSWORD }}
        nowInstallInstance: ${{ secrets.NOW_TEST_INSTANCE }}
        appSysID: ${{ secrets.APP_SYS_ID }}
        appScope: ${{ secrets.APP_SCOPE }}
