name: ServiceNow Pull Request Pipeline

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Apply changes to dev instance
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: ServiceNow CI/CD Apply Changes
        uses: ServiceNow/sncicd-apply-changes@1.2.1
        env:
          nowUsername: ${{ secrets.SN_DEV_USERNAME }}
          nowPassword: ${{ secrets.SN_DEV_PASSWORD }}
          nowSourceInstance: ${{ secrets.NOW_DEV_INSTANCE }}
          appSysID: ${{ secrets.APP_SYS_ID }}
